# WHERE DEPLOY
version: '2'
services:

  wherecron:
    hostname: wherecron
    image: xordiv/docker-alpine-cron
    volumes:
      - ./wherecron_data/crontabs:/etc/cron.d
      - ./wherecron_data/scripts:/scripts
