# WHERE DEPLOY
version: '2'
services:
  wheredb:
    hostname: wheredb
    image: sylviefiat/alpine-mysql
    volumes:
      - ./wheredb_data:/var/lib/mysql
    ports:
      - "3506:3306"
    environment:
      - MYSQL_USER=docker
      - MYSQL_USER_PWD=docker
      - MYSQL_ROOT_PWD=docker
      - MYSQL_USER_DB=baleines

  wherecron:
    hostname: wherecron
    image: sylviefiat/docker-alpine-cron
    ports:
      - "29:25"
    volumes:
      - ./wherecron_data/crontabs:/etc/crontabs/
      - ./wherecron_data/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - wheredb:wheredb

networks:
  default:
    external:
      name: entropiedeploy_default
